"""microsoft sign-in

Revision ID: f70a334a550c
Revises: d7217d51b08e
Create Date: 2026-08-20 11:56:45.711313
"""
from alembic import op
import sqlalchemy as sa


revision = 'f70a334a550c'
down_revision = 'd7217d51b08e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('microsoft_oid', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_teacher_microsoft_oid', ['microsoft_oid'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_teacher_microsoft_oid', type_='unique')
        batch_op.drop_column('microsoft_oid')

    # ### end Alembic commands ###
